solves 404 error page
ArnabChatterjee20k/PickPalette-PaletteFromImage pull request #33
Opened 2024-05-26 18:40 UTC by AMISH-KHAN

# Title
Error 404 page added

## Description

I have added error 404 page as discussed

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/123164129/bc942674-fefe-4fbc-8f59-b61a24ed67ad)

---
## Issue Ticket Number
Fixes #19 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

2024-05-27 05:18 UTC, ArnabChatterjee20k commented
@AMISH-KHAN share a video of the page in all responsive views

2024-05-27 05:20 UTC, ArnabChatterjee20k requested changes

2024-05-27 05:20 UTC, ArnabChatterjee20k commented on src/App.jsx
> +import NotFound from "./Page/NotFound/NotFound";
lazy load this component otherwise the component will load unnecessarily.

2024-05-27 11:38 UTC, AMISH-KHAN commented
> @AMISH-KHAN share a video of the page in all responsive views

@ArnabChatterjee20k  here's the video of responsiveness


https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/123164129/7fb37807-ea5f-4ce0-a5cc-738361245887

I have also implemented the lazy load please review

2024-05-29 15:16 UTC, merged

2024-05-29 15:16 UTC, ArnabChatterjee20k commented
Thanks for contributing